name        : cosmic-settings-daemon
version     : 1.9.0
release     : 53
summary     : Cosmic Settings Daemon
component   : desktop
license     : GPL-3.0
homepage    : https://github.com/pop-os/cosmic-settings-daemon

description : |
    Cosmic Settings Daemon

source      :
    - https://github.com/pop-os/cosmic-settings-daemon/archive/refs/tags/epoch-1.9.0.tar.gz : 69e34f67c1ae727a75b9a75e7901738adf2779ca1024f53d280d474d1af9ff6c

networking  : true

builddeps   :
    - just
    - mold
    - rust
    - pkgconfig(libgeoclue-2.0)
    - pkgconfig(libinput)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libpulse)
    - pkgconfig(libudev)
    - pkgconfig(xkbcommon)

rundeps     :
    - cosmic-sound-theme
    - geoclue
    - power-profiles-daemon

setup       : |
    unset DISPLAY SUDO_USER SUDO_GID SUDO_UID SUDO_COMMAND CDPATH
    unset RUSTC_WRAPPER
    export GEOCLUE_AGENT="$(realpath $libdir/geoclue/geoclue-2.0/demos/agent)"
    cargo fetch --locked

build       : |
    unset RUSTC_WRAPPER
    export GEOCLUE_AGENT="$(realpath $libdir/geoclue/geoclue-2.0/demos/agent)"
    cargo build --release --locked --bin cosmic-settings-daemon

install     : |
    make install DESTDIR="$installdir" prefix="/usr" CARGO_TARGET_DIR="target"
